name: trying-bayesian-on-pace
method: bayes
metric:
  name: eval/episode_reward
  goal: maximize
parameters:
  learning_rate:
    values: [5e-3, 1e-3, 5e-4, 1e-4]
  discounting:
    values: [0.97, 0.98, 0.99]
  num_envs:
    values: [1024, 2048, 4096]
  num_minibatches:
    values: [8, 16, 32]
  rollouts_per_step:
    values: [1]
  clipping_epsilon:
    values: [0.1, 0.2, 0.3]
  unroll_length:
    values: [20, 25, 30]
  resamples_per_epoch:
    values: [1, 4, 8]
  num_tradeoffs:
    values: [8]
  num_designs:
    values: [8]
