# Training config for the `mo_design_hypernetwork` algorithm on CodesignCheetah.
#
# H_\pi(d, w) = \pi(a | s)
name: 6d-height-only-design-test
save_dir: scratch/logs/codesign/results/Sep03
description: "N/A"
algorithm: design_hypernetwork
env: "MOCodesignCheetah"
backend: jnp # always jnp for training

env_config:
  ctrl_dt: 0.01
  sim_dt: 0.01
  action_scale: 1.0
  reward:
    weights:
      run:        1.0
      height:     10.0
      energy:     0.00003
      alive:      1.0
      done:       0
    optimization:
      objectives:        [['run'], ['energy'], ['height']]
      shared_objectives: ['alive']
      labels:            ['Running Speed', 'Height']
      default_scalarization: [0.0, 0.0, 1.0]
  termination:
    enabled: true
    base_height: 0.2
  codesign:
    default_design: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    low:  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    high: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

learning_params:
  ppo_params:
    num_timesteps: 5000000000
    episode_length: 500
    num_parallel_envs: 4096
    unroll_length: 20
    batch_size: 128
    num_minibatches: 32
    num_updates_per_batch: 4
    learning_rate: 0.0001
    entropy_cost: 0.01
    discounting: 0.98
    reward_scaling: 1.0
    clipping_epsilon: 0.3
    gae_lambda: 0.95
    max_grad_norm: 1.0
    normalize_advantage: true
    normalize_observations: true
    num_evals: 30
    num_eval_envs: 256
    deterministic_eval: true
    seed: 0
    value_loss_type: mse
    huber_delta: 1.0
    batching_strategy: design
  network_params:
    hypersize: [512, 512]
    num_features: 64
    policy_hidden_layer_sizes: [64, 64]
    value_hidden_layer_sizes:  [64, 64]
  design_sampling:
    num_designs: 32 # How many different designs to sample in each epoch
    per_cell: 128 # How many times each design should be trialed
    resamples_per_epoch: 8
    sampling: random