"""Shared helpers for ``codesign`` (design construction, model batching, plotting)."""

from codesign.utils.grid import Grid, sample_tradeoffs_cpu
from codesign.utils.model import (
    uniform_design_sweep,
    stack_models,
    build_batched_model,
    sample_designs,
    maximin_designs,
    min_design_gap,
    normalize_design,
    unnormalize_design,
    total_mass,
)
from codesign.utils.plotting import (
    design_colors,
    get_colors,
    objective_labels,
    plot_design_paretos,
    plot_design_objective_pareto,
    plot_sequential_design_paretos,
    plot_mo_design_progress,
    plot_mean_hv_progress,
    plot_design_pareto_progress,
    plot_design_rewards,
    plot_design_learning_curves,
    plot_design_rewards_progress,
    dress_axis,
    plot_design_sweep_1d,
    plot_design_predictor,
    predictor_density,
    MODesignTrainingPlottingInfo,
)

__all__ = [
    "Grid",
    "uniform_design_sweep",
    "stack_models",
    "build_batched_model",
    "sample_designs",
    "sample_tradeoffs_cpu",
    "maximin_designs",
    "min_design_gap",
    "normalize_design",
    "unnormalize_design",
    "total_mass",
    "design_colors",
    "get_colors",
    "objective_labels",
    "plot_design_paretos",
    "plot_design_objective_pareto",
    "plot_sequential_design_paretos",
    "plot_mo_design_progress",
    "MODesignTrainingPlottingInfo",
    "plot_mean_hv_progress",
    "plot_design_pareto_progress",
    "plot_design_rewards",
    "plot_design_learning_curves",
    "plot_design_rewards_progress",
    "dress_axis",
    "plot_design_sweep_1d",
    "plot_design_predictor",
    "predictor_density",
]
